name: Build and Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and release'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Determine the tag to build
      - name: Determine tag
        id: determine_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${{ github.ref_name }}"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      # Checkout the specific tag
      - name: Checkout tag
        run: |
          echo "Checking out tag $TAG"
          git checkout $TAG

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build the project
        run: npm run build

      # Determine the version
      - name: Print TAG value
        run: echo "TAG is $TAG"

      # Extract release notes for the current version
      - name: Extract release notes
        id: release_notes
        run: |
          sed -i 's/\r$//' CHANGELOG.md
          echo "Running: awk \"/^## ${TAG}$/,/^## /\" CHANGELOG.md"

          awk "/^## ${TAG}$/,/^## [^#]/" CHANGELOG.md | sed '$d' > release_notes.txt

          if [ ! -s release_notes.txt ]; then
            echo "No matching release notes found for $TAG" > release_notes.txt
          fi

          echo "Release notes extracted:"
          cat release_notes.txt

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: "Release ${{ env.TAG }}"
          body_path: release_notes.txt
          draft: false
          prerelease: false

      # Upload build artifact to GitHub Release
      - name: Upload build artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: poe2-trade-butler.zip
          asset_name: poe2-trade-butler.zip
          asset_content_type: application/zip
