name: Publish schema on GitHub Release

on:
  workflow_run:
    workflows: ["release-please.yml"]
    types: [completed]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to publish (e.g., v1.2.3)'
        required: true
        default: ''
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Resolve target tag
        id: tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ inputs.release_tag }}"
          else
            # 방금 publish된 최신 릴리즈 태그를 조회 (정식/프리릴리즈 모두 허용하려면 아래 주석 풀기)
            # TAG=$(gh api repos/${{ github.repository }}/releases --jq 'map(select(.draft==false)) | sort_by(.created_at) | last.tag_name')
            TAG=$(gh api repos/${{ github.repository }}/releases/latest --jq .tag_name)
          fi
          
          if [ -z "$TAG" ]; then
            echo "No tag resolved. Abort."
            exit 1
          fi
          
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Resolved tag: $TAG"

      - name: Checkout source at resolved tag
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.tag.outputs.tag }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Export JSON Schema
        run: npm run export:schema

      - name: Read version from package.json
        id: pkg
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Prepare publish directory
        run: |
          mkdir -p public/simple-server/${{ steps.pkg.outputs.version }}/
          mv SimplifiedFolder.schema.json public/simple-server/${{ steps.pkg.outputs.version }}/
          cp -f public/simple-server/${{ steps.pkg.outputs.version }}/SimplifiedFolder.schema.json public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
